name: Flaky E2E tests detector

on:
  pull_request:
    paths:
      - '**/*.test-e2e.*'

# when new commit is pushed to a branch, cancel previous runs
# https://stackoverflow.com/a/67939898/580181
concurrency:
  group: flaky-e2e-detector-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    strategy:
      matrix:
        node: ['20']
        os: [ubicloud-standard-16]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm exec playwright install --with-deps chromium
        working-directory: ./packages/app
      - run: pnpm run test-e2e --repeat-each 4 --retries 2
        working-directory: ./packages/app
        env:
          TENDERLY_API_KEY: '${{ secrets.TENDERLY_API_KEY }}'
          TENDERLY_ACCOUNT: phoenixlabs
          TENDERLY_PROJECT: sparklend
          PLAYWRIGHT_TRACE: 1

      - name: Upload report to GitHub Actions Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: flaky-test-e2e-report
          path: packages/app/playwright-report
          retention-days: 3
